[general]

live_config_reload = true

[window]
opacity = 0.0
decorations = "none"

[window.padding]
x = 200
y = 200

[colors.primary]

background = "#000000"

[colors]

draw_bold_text_with_bright_colors = true

transparent_background_colors = true

