general {
disable_loading_bar = false
}

background {
color = rgba(0,0,0,0.9)
}

input-field {
monitor =
size = 200, 50
outline_thickness = 2
outer_color = rgb(151515)
inner_color = rgb(200, 200, 200)
}

label {
monitor =
text = $TIME
color = rgb(1,1,1)
font_size = 50
font_family = JetBrainsMono NF
position = 0, 140
halign = center
valign = center
}
