--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/lucas/wallpapers/wallhaven-yq769k.png"

-- Special
background="#0a0300"
foreground="#c1c0bf"
cursor="#c1c0bf"

-- Colors
color0="#0a0300"
color1="#32433B"
color2="#544E32"
color3="#8D3208"
color4="#AC5413"
color5="#A05618"
color6="#C7701B"
color7="#c1c0bf"
color8="#655852"
color9="#32433B"
color10="#544E32"
color11="#8D3208"
color12="#AC5413"
color13="#A05618"
color14="#C7701B"
color15="#c1c0bf"
