# Shell variables
# Generated by 'wal'
wallpaper="/home/lucas/wallpapers/wallhaven-yq769k.png"

# Special
background='#0a0300'
foreground='#c1c0bf'
cursor='#c1c0bf'

# Colors
color0='#0a0300'
color1='#32433B'
color2='#544E32'
color3='#8D3208'
color4='#AC5413'
color5='#A05618'
color6='#C7701B'
color7='#c1c0bf'
color8='#655852'
color9='#32433B'
color10='#544E32'
color11='#8D3208'
color12='#AC5413'
color13='#A05618'
color14='#C7701B'
color15='#c1c0bf'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
